name: Provider Request
description: Request support for a new LLM provider
title: "[Provider] "
labels: ["enhancement", "provider"]
body:
  - type: input
    id: provider-name
    attributes:
      label: Provider Name
      description: Name of the LLM provider (e.g. Together AI, Fireworks)
      placeholder: Provider Name
    validations:
      required: true
  - type: input
    id: api-docs
    attributes:
      label: API Documentation URL
      description: Link to the provider's API documentation
      placeholder: https://docs.example.com/api
    validations:
      required: true
  - type: dropdown
    id: openai-compatible
    attributes:
      label: OpenAI-Compatible API?
      description: Does this provider offer an OpenAI-compatible chat completions endpoint?
      options:
        - "Yes"
        - "No"
        - "Partially"
    validations:
      required: true
  - type: input
    id: base-url
    attributes:
      label: Base URL
      description: The API base URL (if OpenAI-compatible)
      placeholder: https://api.example.com/v1
    validations:
      required: false
  - type: input
    id: default-model
    attributes:
      label: Default Model
      description: Recommended default model ID
      placeholder: provider/model-name
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other details (pricing, special features, auth requirements)
    validations:
      required: false
